package pcd.ass03.ex01.utils;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * This class represents a generic combination, generated by a player.
 */
public final class Combination {
    // from 0 to 10
    private static final int COMBINATION_RANGE = 10;

    private final List<Integer> combination;

    private Combination(final int combinationSize) {
        final Random random = new Random();

        this.combination = new ArrayList<>();
        for (int i = 0; i < combinationSize; i++) {
            this.combination.add(random.nextInt(COMBINATION_RANGE));
        }
    }

    public List<Integer> getCombination() {
        return combination;
    }

    /**
     * Checks whether the passed combination is equal to the current.
     * @param toCompare the combination to compare with the current.
     * @return true if the combination are equals, false otherwise.
     */
    public boolean compare(final Combination toCompare) {
        return combination.equals(toCompare.getCombination());
    }

    /**
     * Returns the number of cyphers that are in the same place, with the same value.
     * @param toCompare the combination to compare with the current.
     * @return the number of cyphers that are in the same place, with the same value.
     *         If the size of the lists are different, it returns 0.
     */
    public int computeGuessedPositions(final Combination toCompare) {
        int nOfGuessedPositions = 0;

        if (combWithDifferentSize(toCompare)) {
            return nOfGuessedPositions;
        }

        for (int i = 0; i < combination.size(); i++) {
            if (combination.get(i).equals(toCompare.getCombination().get(i))) {
                nOfGuessedPositions++;
            }
        }
        return nOfGuessedPositions;
    }

    /**
     * Returns the number of cyphers that are in common between combination, but NOT
     * in the same place.
     * @param toCompare the combination to compare with the current.
     * @return the number of cyphers that are in common between combination, but NOT
     *         in the same place. If the size of the lists are different, it returns 0.
     */
    public int computeGuessedCyphers(final Combination toCompare) {
        int nOfGuessedCyphers = 0;

        if (combWithDifferentSize(toCompare)) {
            return nOfGuessedCyphers;
        }

        for (int i = 0; i < combination.size(); i++) {
            if (combination.contains(toCompare.getCombination().get(i))
                    && !combination.get(i).equals(toCompare.getCombination().get(i))) {
                nOfGuessedCyphers++;
            }
        }
        return nOfGuessedCyphers;
    }

    /**
     * Checks whether combinations have the same size.
     * @param toCompare the combination to compare with the current.
     * @return true if combinations have the same size, false otherwise.
     */
    private boolean combWithDifferentSize(final Combination toCompare) {
        return combination.size() != toCompare.getCombination().size();
    }

    /**
     * Factory to generate a random combination.
     * @param combinationSize the number of chyphers of the combination
     * @return the new combination
     */
    public Combination of(final int combinationSize) {
        return new Combination(combinationSize);
    }
}
